#include <stdexcept>
#include <cstdlib>
// Copyright (c) 2011 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.
//
// Decodes the blocks generated by block_builder.cc.

#include "table/block.h"

#include <algorithm>
#include <cstdint>
#include <vector>

#include "leveldb/comparator.h"
#include "table/format.h"
#include "util/coding.h"
#include "util/logging.h"

namespace leveldb {

inline uint32_t Block::NumRestarts() const {
    __builtin_trap() /* STUB: not implemented */;
}

Block::Block(const BlockContents& contents)
    : data_(contents.data.data()),
      size_(contents.data.size()),
      owned_(contents.heap_allocated) {
    __builtin_trap() /* STUB: not implemented */;
}

Block::~Block() {
  if (owned_) {
    delete[] data_;
  }
}

// Helper routine: decode the next block entry starting at "p",
// storing the number of shared key bytes, non_shared key bytes,
// and the length of the value in "*shared", "*non_shared", and
// "*value_length", respectively.  Will not dereference past "limit".
//
// If any errors are detected, returns nullptr.  Otherwise, returns a
// pointer to the key delta (just past the three decoded values).
static inline const char* DecodeEntry(const char* p, const char* limit,
                                      uint32_t* shared, uint32_t* non_shared,
                                      uint32_t* value_length) {
    __builtin_trap() /* STUB: not implemented */;
}

class Block::Iter : public Iterator {
 private:
  const Comparator* const comparator_;
  const char* const data_;       // underlying block contents
  uint32_t const restarts_;      // Offset of restart array (list of fixed32)
  uint32_t const num_restarts_;  // Number of uint32_t entries in restart array

  // current_ is offset in data_ of current entry.  >= restarts_ if !Valid
  uint32_t current_;
  uint32_t restart_index_;  // Index of restart block in which current_ falls
  std::string key_;
  Slice value_;
  Status status_;

  inline int Compare(const Slice& a, const Slice& b) const {
    __builtin_trap() /* STUB: not implemented */;
}

  // Return the offset in data_ just past the end of the current entry.
  inline uint32_t NextEntryOffset() const {
    __builtin_trap() /* STUB: not implemented */;
}

  uint32_t GetRestartPoint(uint32_t index) {
    __builtin_trap() /* STUB: not implemented */;
}

  void SeekToRestartPoint(uint32_t index) {
    __builtin_trap() /* STUB: not implemented */;
}

 public:
  Iter(const Comparator* comparator, const char* data, uint32_t restarts,
       uint32_t num_restarts)
      : comparator_(comparator),
        data_(data),
        restarts_(restarts),
        num_restarts_(num_restarts),
        current_(restarts_),
        restart_index_(num_restarts_) {
    __builtin_trap() /* STUB: not implemented */;
}

  bool Valid() const override {
    __builtin_trap() /* STUB: not implemented */;
}
  Status status() const override {
    __builtin_trap() /* STUB: not implemented */;
}
  Slice key() const override {
    __builtin_trap() /* STUB: not implemented */;
}
  Slice value() const override {
    __builtin_trap() /* STUB: not implemented */;
}

  void Next() override {
    __builtin_trap() /* STUB: not implemented */;
}

  void Prev() override {
    __builtin_trap() /* STUB: not implemented */;
}

  void Seek(const Slice& target) override {
    __builtin_trap() /* STUB: not implemented */;
}

  void SeekToFirst() override {
    __builtin_trap() /* STUB: not implemented */;
}

  void SeekToLast() override {
    __builtin_trap() /* STUB: not implemented */;
}

 private:
  void CorruptionError() {
    __builtin_trap() /* STUB: not implemented */;
}

  bool ParseNextKey() {
    __builtin_trap() /* STUB: not implemented */;
}
};

Iterator* Block::NewIterator(const Comparator* comparator) {
    __builtin_trap() /* STUB: not implemented */;
}

}  // namespace leveldb
